// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Modules.Shell.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.Modules.Shell.Migrations
{
    [DbContext(typeof(ShellDbContext))]
    partial class ShellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ScreenTimeTracker.Modules.Shell.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SilentStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UIOpenMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WindowDestroyOnClose")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shell_UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AutoStart = false,
                            Language = "en-US",
                            SilentStart = false,
                            UIOpenMode = 0,
                            WindowDestroyOnClose = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
