// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Modules.ScreenTime.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.Modules.ScreenTime.Migrations
{
    [DbContext(typeof(ScreenTimeDbContext))]
    partial class ScreenTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoUpdateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAutoUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppCategoryId");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("ScreenTime_Apps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AppCategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Represents unknown or restricted apps",
                            IsAutoUpdateEnabled = false,
                            IsSystem = true,
                            LastAutoUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unknown",
                            ProcessName = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AppCategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Shows when the user is idle",
                            IsAutoUpdateEnabled = false,
                            IsSystem = true,
                            LastAutoUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Idle",
                            ProcessName = "Idle"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_AppCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsSystem = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppUsageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("AppId", "EndTime");

                    b.ToTable("ScreenTime_AppUsageSessions");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActiveSessionAutoSaveInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppIconDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppInfoStaleThreshold")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayCutoffHour")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("IdleDetectionPollingInterval")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("IdleThreshold")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIdleDetectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("MinValidSessionDuration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SessionMergeTolerance")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SessionOptimizationInterval")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ActiveSessionAutoSaveInterval = new TimeSpan(0, 0, 0, 15, 0),
                            AppIconDirectory = "./Data/Icons",
                            AppInfoStaleThreshold = new TimeSpan(1, 0, 0, 0, 0),
                            DayCutoffHour = 5,
                            IdleDetectionPollingInterval = new TimeSpan(0, 0, 0, 10, 0),
                            IdleThreshold = new TimeSpan(0, 0, 10, 0, 0),
                            IsIdleDetectionEnabled = false,
                            MinValidSessionDuration = new TimeSpan(0, 0, 0, 5, 0),
                            SessionMergeTolerance = new TimeSpan(0, 0, 0, 6, 0),
                            SessionOptimizationInterval = new TimeSpan(0, 0, 10, 0, 0)
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.App", b =>
                {
                    b.HasOne("ScreenTimeTracker.Modules.ScreenTime.Domain.AppCategory", "AppCategory")
                        .WithMany()
                        .HasForeignKey("AppCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppCategory");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppUsageSession", b =>
                {
                    b.HasOne("ScreenTimeTracker.Modules.ScreenTime.Domain.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });
#pragma warning restore 612, 618
        }
    }
}
