// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Modules.ScreenTime.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.Modules.ScreenTime.Migrations
{
    [DbContext(typeof(ScreenTimeDbContext))]
    partial class ScreenTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("LoggedAt")
                        .IsUnique();

                    b.ToTable("ScreenTime_ActivityLogs");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoUpdateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAutoUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppCategoryId");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("ScreenTime_Apps");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_AppCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsSystem = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppHourlyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hour");

                    b.HasIndex("AppId", "Hour")
                        .IsUnique();

                    b.ToTable("ScreenTime_AppHourlyUsages");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AggregationInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppIconDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppInfoStaleThreshold")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IdleDetection")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("IdleTimeout")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SamplingInterval")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AggregationInterval = new TimeSpan(0, 1, 0, 0, 0),
                            AppIconDirectory = "./Data/Icons",
                            AppInfoStaleThreshold = new TimeSpan(1, 0, 0, 0, 0),
                            IdleDetection = false,
                            IdleTimeout = new TimeSpan(0, 0, 10, 0, 0),
                            SamplingInterval = new TimeSpan(0, 0, 0, 1, 0)
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.ActivityLog", b =>
                {
                    b.HasOne("ScreenTimeTracker.Modules.ScreenTime.Domain.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.App", b =>
                {
                    b.HasOne("ScreenTimeTracker.Modules.ScreenTime.Domain.AppCategory", "AppCategory")
                        .WithMany()
                        .HasForeignKey("AppCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppCategory");
                });

            modelBuilder.Entity("ScreenTimeTracker.Modules.ScreenTime.Domain.AppHourlyUsage", b =>
                {
                    b.HasOne("ScreenTimeTracker.Modules.ScreenTime.Domain.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });
#pragma warning restore 612, 618
        }
    }
}
