// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Modules.AppBehavior.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.Modules.AppBehavior.Migrations
{
    [DbContext(typeof(AppBehaviorDbContext))]
    [Migration("20260415163904_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ScreenTimeTracker.Modules.AppBehavior.Domain.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultUIOpenMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoStartEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSilentStartEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldDestroyWindowOnClose")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppBehavior_UserPreferences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DefaultUIOpenMode = 0,
                            IsAutoStartEnabled = false,
                            IsSilentStartEnabled = false,
                            Language = "en-US",
                            ShouldDestroyWindowOnClose = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
