// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Hosts.Desktop.LocalSettings.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.Hosts.Desktop.Migrations
{
    [DbContext(typeof(LocalSettingsDbContext))]
    partial class LocalSettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ScreenTimeTracker.Hosts.Desktop.LocalSettings.Domain.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultUIOpenMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoStartEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSilentStartEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldDestroyWindowOnClose")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Desktop_LocalSettings_AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DefaultUIOpenMode = 0,
                            IsAutoStartEnabled = false,
                            IsSilentStartEnabled = false,
                            Language = "en-US",
                            ShouldDestroyWindowOnClose = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
